spring.application.name=project-backend

## Change port if 8080 is blocked
server.port=8080

## PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=postgres
spring.datasource.password=2918
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
